import {
  ColumnType,
  TableColumn,
  TableDataType,
  CellTextAlign,
} from "./tableTypes";

export const testColumns: TableColumn[] = [
  {
    id: "product_name",
    label: "Product",
    minWidth: 80,
    align: CellTextAlign.left,
    type: ColumnType.string,
    highlight: true,
    searchable: true,
  },
  {
    id: "color",
    label: "Color",
    minWidth: 80,
    align: CellTextAlign.left,
    type: ColumnType.string,
    highlight: false,
    //   filtering: true,
    searchable: true,
  },
  {
    id: "category",
    label: "Category",
    minWidth: 80,
    align: CellTextAlign.left,
    type: ColumnType.string,
    highlight: false,
    filtering: true,
  },
  {
    id: "accessories",
    label: "Accessories",
    minWidth: 80,
    // align: CellTextAlign.left,
    type: ColumnType.boolean,
    highlight: false,
    //   invisible: true,
    filtering: true,
  },
  {
    id: "available",
    label: "Available",
    minWidth: 80,
    // align: CellTextAlign.left,
    type: ColumnType.boolean,
    highlight: false,
  },
  {
    id: "price",
    label: "Price",
    minWidth: 80,
    align: CellTextAlign.right,
    type: ColumnType.string,
    highlight: true,
  },
  {
    id: "weight",
    label: "Weight",
    minWidth: 80,
    // align: CellTextAlign.left,
    type: ColumnType.string,
    highlight: false,
  },
];

export const testData: TableDataType = [
  {
    product_name: "Prod1",
    color: "Silver",
    category: "Laptop",
    accessories: true,
    available: true,
    price: "$2999",
    weight: "3.0 lb.",
  },
  {
    product_name: "Prod2",
    color: "White",
    category: "Laptop PC",
    accessories: false,
    available: true,
    price: "$1999",
    weight: "1.0 lb.",
  },
  {
    product_name: "Prod3",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$99",
    weight: "0.2 lb.",
  },
  {
    product_name: "Prod4",
    color: "Black",
    category: "Watches",
    accessories: true,
    available: false,
    price: "$199",
    weight: "0.12 lb.",
  },
  {
    product_name: "Prod5",
    color: "Silver",
    category: "PC",
    accessories: true,
    available: true,
    price: "$2999",
    weight: "7.0 lb.",
  },
  {
    product_name: "Prod6",
    color: "White",
    category: "Accessories",
    accessories: false,
    available: true,
    price: "$399",
    weight: "38 g",
  },
  {
    product_name: "Prod7",
    color: "Gold",
    category: "Tablet",
    accessories: false,
    available: true,
    price: "$699",
    weight: "1.3 lb.",
  },
  {
    product_name: "Prod8",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: true,
    price: "$99",
    weight: "453 g",
  },
  {
    product_name: "Prod9",
    color: "Black",
    category: "TV",
    accessories: true,
    available: false,
    price: "$179",
    weight: "1.78 lb.",
  },
  {
    product_name: "Prod10",
    color: "Silver",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$29",
    weight: "53 g",
  },
  {
    product_name: "Prod11",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$99",
    weight: "0.2 lb.",
  },
  {
    product_name: "Prod12",
    color: "Black",
    category: "Watches",
    accessories: true,
    available: false,
    price: "$199",
    weight: "0.12 lb.",
  },
  {
    product_name: "Prod13",
    color: "Silver",
    category: "PC",
    accessories: true,
    available: true,
    price: "$2999",
    weight: "7.0 lb.",
  },
  {
    product_name: "Prod14",
    color: "White",
    category: "Accessories",
    accessories: false,
    available: true,
    price: "$399",
    weight: "38 g",
  },
  {
    product_name: "Prod15",
    color: "Gold",
    category: "Tablet",
    accessories: false,
    available: true,
    price: "$699",
    weight: "1.3 lb.",
  },
  {
    product_name: "Prod16",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: true,
    price: "$99",
    weight: "453 g",
  },
  {
    product_name: "Prod17",
    color: "Black",
    category: "TV",
    accessories: true,
    available: false,
    price: "$179",
    weight: "1.78 lb.",
  },
  {
    product_name: "Prod18",
    color: "Silver",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$29",
    weight: "53 g",
  },
  {
    product_name: "Prod19",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$99",
    weight: "0.2 lb.",
  },
  {
    product_name: "Prod20",
    color: "Black",
    category: "Watches",
    accessories: true,
    available: false,
    price: "$199",
    weight: "0.12 lb.",
  },
  {
    product_name: "Prod21",
    color: "Silver",
    category: "PC",
    accessories: true,
    available: true,
    price: "$2999",
    weight: "7.0 lb.",
  },
  {
    product_name: "Prod22",
    color: "White",
    category: "Accessories",
    accessories: false,
    available: true,
    price: "$399",
    weight: "38 g",
  },
  {
    product_name: "Prod23",
    color: "Gold",
    category: "Tablet",
    accessories: false,
    available: true,
    price: "$699",
    weight: "1.3 lb.",
  },
  {
    product_name: "Prod24",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: true,
    price: "$99",
    weight: "453 g",
  },
  {
    product_name: "Prod25",
    color: "Black",
    category: "TV",
    accessories: true,
    available: false,
    price: "$179",
    weight: "1.78 lb.",
  },
  {
    product_name: "Prod26",
    color: "Silver",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$29",
    weight: "53 g",
  },
  {
    product_name: "Prod27",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$99",
    weight: "0.2 lb.",
  },
  {
    product_name: "Prod28",
    color: "Black",
    category: "Watches",
    accessories: true,
    available: false,
    price: "$199",
    weight: "0.12 lb.",
  },
  {
    product_name: "Prod29",
    color: "Silver",
    category: "PC",
    accessories: true,
    available: true,
    price: "$2999",
    weight: "7.0 lb.",
  },
  {
    product_name: "Prod30",
    color: "White",
    category: "Accessories",
    accessories: false,
    available: true,
    price: "$399",
    weight: "38 g",
  },
  {
    product_name: "Prod31",
    color: "Gold",
    category: "Tablet",
    accessories: false,
    available: true,
    price: "$699",
    weight: "1.3 lb.",
  },
  {
    product_name: "Prod32",
    color: "Black",
    category: "Accessories",
    accessories: true,
    available: true,
    price: "$99",
    weight: "453 g",
  },
  {
    product_name: "Prod33",
    color: "Black",
    category: "TV",
    accessories: true,
    available: false,
    price: "$179",
    weight: "1.78 lb.",
  },
  {
    product_name: "Prod34",
    color: "Silver",
    category: "Accessories",
    accessories: true,
    available: false,
    price: "$29",
    weight: "53 g",
  },
];
